---
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: signalfx
  namespace: istio-system
spec:
  adapter: signalfx
  connection:
    address: "signalfx-adapter:8080"  # Fill in with actual hostname of adapter service
  params:
    access_token: "{MY_ACCESS_TOKEN}"
    ingest_url: "https://ingest.signalfx.com"  # Fill in with base ingest URL or remove to use default
    datapoint_interval: 10s
    enable_metrics: true
    enable_tracing: true
    metrics:
    - name: requestcount.instance.istio-system
      type: COUNTER
    - name: requestduration.instance.istio-system
      type: HISTOGRAM
    - name: requestsize.instance.istio-system
      type: COUNTER
    - name: responsesize.instance.istio-system
      type: COUNTER
    - name: tcpbytesent.instance.istio-system
      type: COUNTER
    - name: tcpbytereceived.instance.istio-system
      type: COUNTER
    tracing:
      buffer_size: 1000
      sample_probability: 1.0
      localEndpointNameTagKey: source.workload.name
      localEndpointIpTagKey: source.ip
      remoteEndpointNameTagKey: destination.workload.name
      remoteEndpointIpTagKey: destination.ip
